name: media service ci

on:
  push:
    branches: [ "main" ]
    paths:
      - "media/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/media-ci.yaml"
      - "pom.xml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "media/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/media-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          
      - name: Run Gitleaks Scan
        uses: ./.github/workflows/gitleak
        
      # TODO: Chờ anh Thịnh hoàn thành Action Snyk để copy vào đây
      
      - uses: ./.github/workflows/actions
      
      - name: Run Maven Test Command
        run: mvn clean test jacoco:report -pl media -am
        
      - name: Run Maven Checkstyle
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        run: mvn checkstyle:checkstyle -pl media -am -Dcheckstyle.output.file=media-checkstyle-result.xml
        
      - name: Upload Checkstyle Result
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/media-checkstyle-result.xml'
          
      - name: Analyze with sonar cloud
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f media
        
      - name: Quality Gate (Coverage >= 70%)
        run: |
          awk -F"," 'NR>1 { missed += $4; covered += $5 } END {
            if (missed+covered > 0) coverage = (covered/(missed+covered))*100
            else coverage = 0
            print "Code Coverage: " coverage "%"
            if (coverage < 70) {
              print "Coverage is below 70%. Failing the pipeline."
              exit 1
            }
          }' media/target/site/jacoco/jacoco.csv

      - name: Test Results
        uses: dorny/test-reporter@v1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
        with:
          name: Media-Service-Unit-Test-Results
          path: "media/**/*-reports/TEST*.xml"
          reporter: java-junit

      - name: OWASP Dependency Check
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'yas'
          path: '.'
          format: 'HTML'

      - name: Upload OWASP Dependency Check results
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: actions/upload-artifact@master
        with:
          name: OWASP Dependency Check Report
          path: ${{github.workspace}}/reports
          
      - name: Add coverage report to PR
        uses: madrapps/jacoco-report@v1.6.1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        with:
          paths: ${{github.workspace}}/media/target/site/jacoco/jacoco.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 70
          min-coverage-changed-files: 60
          title: 'Media Coverage Report'
          update-comment: true

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/workflows/actions
        
      - name: Run Maven Build Command
        run: mvn clean install -DskipTests -pl media -am
        
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./media
          push: true
          tags: ghcr.io/nashtech-garage/yas-media:latest